### ISSUE TITLE
using xsd2html2xml from Java: XSL compilation error

### ISSUE THREAD

**Issue by kgi-github** [MichielCM/xsd2html2xml#17]
Hi Michiel,

I did try email you, but perhaps this is a better way to raise the issue below. Sorry if you're getting this twice!

Firstly, thanks for making your code available. I was able to get it working on the client side (using javascript) in Firefox (although Chrome didn't work for some reason).
 
I then tried doing the XSL processing on the server side, using Java's built in XSL transformer (which I believe is xalan). But I encounter an XSL compilation error "namespaces.xsl: line 80: Second argument to document() function must be a node-set", which is listed in full below. My simplified java main method (note "my-directory" needs replacing) is:
 
public static void main(String[] args) {
        try {
            File stylesheet = new File("my-directory/xsd2html2xml.xsl");
            StreamSource stylesource = new StreamSource(stylesheet); 
            TransformerFactory transFactory = TransformerFactory.newInstance();
            Transformer transformer = transFactory.newTransformer(stylesource);
        } catch (Exception e) {
            e.printStackTrace();
        }
}
 
I tried the changing the include in xsd2html2xml.xsl to the various utils/nodeset-XXX.xsl files with the same results. I am using version 3.2 of your code. I note your readme says xalan support is full. Am I missing something obvious?!
 
Thanks,
Kevin.
 
--- XSL compilation  error messages when running code above:

Compiler warnings:
  file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/utils/gui-attributes.xsl: line 413: Attribute 'step' outside of element.
  file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/utils/gui-attributes.xsl: line 424: Attribute 'step' outside of element.
  file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/utils/gui-attributes.xsl: line 435: Attribute 'step' outside of element.
  file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/handlers/default-types.xsl: line 135: Attribute 'data-xsd2html2xml-primitive' outside of element.
  file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/handlers/default-types.xsl: line 135: Attribute 'data-xsd2html2xml-primitive' outside of element.
  file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/handlers/default-types.xsl: line 139: Attribute 'data-xsd2html2xml-description' outside of element.
  file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/handlers/default-types.xsl: line 139: Attribute 'data-xsd2html2xml-description' outside of element.
  file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/xsd2html2xml.xsl: line 239: Attribute 'namespace' outside of element.
ERROR:  'Could not compile stylesheet'
FATAL ERROR:  'file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/utils/namespaces.xsl: line 80: Second argument to document() function must be a node-set.'
           :file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/utils/namespaces.xsl: line 80: Second argument to document() function must be a node-set.
javax.xml.transform.TransformerConfigurationException: file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/utils/namespaces.xsl: line 80: Second argument to document() function must be a node-set.
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1059)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:817)
    at com.kgi.test.Main.main(Main.java:21)
Caused by: file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/utils/namespaces.xsl: line 80: Second argument to document() function must be a node-set.
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.DocumentCall.typeCheck(DocumentCall.java:100)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.CopyOf.typeCheck(CopyOf.java:64)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XslElement.typeCheck(XslElement.java:159)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.ForEach.typeCheck(ForEach.java:85)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XslElement.typeCheck(XslElement.java:159)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.Template.typeCheck(Template.java:293)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:654)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:410)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:493)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:570)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1018)
    ... 2 more

file:/home/kgi/programming/eclipseWorkspace/TestXSD2HTML2XML/xsd2html2xml-3.2/utils/namespaces.xsl: line 80: Second argument to document() function must be a node-set.
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.DocumentCall.typeCheck(DocumentCall.java:100)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.CopyOf.typeCheck(CopyOf.java:64)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XslElement.typeCheck(XslElement.java:159)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.ForEach.typeCheck(ForEach.java:85)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XslElement.typeCheck(XslElement.java:159)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.Template.typeCheck(Template.java:293)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:485)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:654)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:410)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:493)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:570)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1018)
    at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:817)
    at com.kgi.test.Main.main(Main.java:21)

**Comment by MichielCM** [comment]
Hi there,

I didn't seem to receive an e-mail, but this is the preferred route to ask for help.

It doesn't look like a compilation errror, but a runtime error. I use Xalan myself in development, and can guarantee the code works fine in a Xalan environment. The error you're getting it probably due to a specific element in your XSD.

The document() function requires a node-set as its second parameter. It seems $root-document is not a nodeset as this point, which should never happen as it is passed from template to template unchanged. Here's a few things you can try:
- determine the data type of $root-document using exsl:data-type(); it it null or RTF or something else?
- explicitly make $root-document a node-set in the document call using exsl:node-set($root-document).
- enable the XSLT stack trace by adding 'stack' to the config-debug parameter in config.xsl (or dynamically), then see which element throws the error and isolate it for easier testing.
- try with Saxon; it gives much better error messages.

I'd like to see the schema that threw this error, but unfortunately I can't promise I'll have time to try and debug it myself.

Best regards,
Michiel

**Comment by kgi-github** [comment]
Hi, 

Thanks for getting back to me. 

Yes it is a java runtime exception, but occurs during the XSL compilation phase by xalan (see the stack trace including near the bottom: 
com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:570)
and the "compiler" warnings near the top). 

Indeed it is before any xsd file is even mentioned (see my "main" method in the original post which is simply creating a transformer but never using it). 

Do any of your suggestions apply to this case? Am I doing something wrong? 

cheers, 
Kevin.

**Comment by MichielCM** [comment]
I see. I've set up the code with a fresh environment and I get the same results you do.

I think it has to do with the level of error reporting set for the Xalan parser. Since XSLT is not a statically typed language there is no way the processor can know beforehand if a parameter or variable contains a node-set. So I think it's just overeager error reporting on Xalan's part.

What works for you, change the problematic line to:
`<xsl:copy-of select="document(string(@schemaLocation), exsl:node-set($root-document))" />`
and make sure you include the `xmlns:exsl="http://exslt.org/common"` declaration in namespaces.xsl root xs:stylesheet element.

**Comment by MichielCM** [comment]
I seem to remember there are several Xalan implementations. Try changing to org.eclipse.persistence.moxy and org.eclipse.persistence.core repositories. This should get you started: https://stackoverflow.com/questions/4340625/where-to-include-jaxb-properties-file

**Comment by kgi-github** [comment]
I can't find an XSL transformer in the org.eclipse.persistence packages, they seem to be concerned with JAXB rather than JAXP. However casting to a node-set worked like a charm. I had to do the same to line 115 of namespaces.xsl.

However I now have another issue regarding types specified in an included xsd file. I have simplified as much as possible.

I have two files. The first is ID.xsd:
```
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
       <xs:simpleType name="ID"> 
               <xs:restriction base="xs:integer"> 
               </xs:restriction> 
       </xs:simpleType> 
</xs:schema>
```

The second is test.xsd:
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="ID.xsd"/>

	<xs:complexType name="Thing">
		<xs:sequence>
			<xs:element name="id" type="ID"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="thing" type="Thing"/>
</xs:schema>
```

This does not produce a form with the integer id field. If I change the root element ("thing") to a type of "ID" there is a field. If I define the ID type in test.xsd file instead of including it, there is a field.

If I must debug this myself, so be it, but if you can help that would be awesome!

cheers,
Kevin.

**Comment by MichielCM** [comment]
That's still a Xalan issue. Or rather, a configuration issue. I get the same results on my fresh installation of Eclipse. But on my development machine Xalan works fine. Also, a fresh install of Saxon Home (https://sourceforge.net/projects/saxon/files/latest/download) with this command works fine:
`java -jar saxon9he.jar -s:test.xsd -xsl:xsd2html2xml.xsl -o:output.html`
It does produce the integer field as it should.

**Comment by kgi-github** [comment]
Thanks. I probably won’t get a chance to try Saxon until tomorrow. What is the difference between xalan in your development environment and a fresh install? Is it a previous version? I’d prefer not to use Saxon as the license is more restrictive.

**Comment by MichielCM** [comment]
I wish I knew. I do know you need the following dependencies and have to use a jaxb.properties file to point Transformer to the correct implementation.
```
  		<dependency>
  			<groupId>xalan</groupId>
  			<artifactId>xalan</artifactId>
  			<version>2.7.2</version>
  		</dependency>
  		<dependency>
  			<groupId>org.eclipse.persistence</groupId>
  			<artifactId>org.eclipse.persistence.moxy</artifactId>
  			<version>2.6.4</version>
  		</dependency>
  		<dependency>
  			<groupId>org.eclipse.persistence</groupId>
  			<artifactId>org.eclipse.persistence.core</artifactId>
  			<version>2.6.4</version>
  		</dependency>
```
If you can't use Saxon you could also opt for libxslt. It has an open license.

**Comment by kgi-github** [comment]
Hi,

So if I download the xalan jar files from http://xalan.apache.org/xalan-j/downloads.html (instead of using the built-in jdk implementation) and use the Interpretive XSL processor (xalan.jar) rather than the compiling XSL processor (xsltc.jar) I get a field. But I don't get the integer field (with the + and - to increment and decrement) that I get if I define the ID type in test.xsd.

The same thing happens when I use the saxon he 9.8.0.15. If I define the ID type in text.xsd I get a field with + and - to set the integer value. However if I instead include the ID.xsd file, I get a plain field with no + and -. Does this mean that some type information has gone missing?

Thanks for the libxslt lead. I'll check it out.

cheers,
Kevin.

**Comment by MichielCM** [comment]
Hi Kevin,

Yep, that's an error. I found what happens (the -primitive attribute reads 'integerxs:integer' instead of 'integer') and so the code does not recognize it needs to create a number field. I found out this is due to the ID.xsd being loaded in twice and the type thus being declared twice.

I'll check it out and fix it ASAP. And by all means, please open new issues for bugs you encounter. I can't promise I'll have time to fix them quickly, but without bug reports the code won't improve at all.

Cheers,
Michiel

**Comment by kgi-github** [comment]
Cool. I wonder if the behaviour where an included file is loaded twice is responsible for the other bug I noticed (which I've just described in a new issue). Keep me posted as to when I can download a fix.

Thanks!
Kevin.

**Comment by kgi-github** [comment]
Thanks, fixes both issues. Shall I leave the closing of issues to you?
